### ISSUE TITLE
Dun Morogh/Wetlands zone crossing note is incorrect

### ISSUE THREAD

**Issue by economou** [leatrix/leatrix-maps-wrath#53]
Thank you for adding the zone crossing arrow from Dun Morogh to Wetlands - I never knew about that path before!

I just want to report that the "You will die!" text is incorrect and could be misleading.  I found a safe way down into the Wetlands on my very first try on a level 1 character (keep going right, basically).  Due to the text, I was expecting to have to spirit res in Wetlands, but I made it to Menethil Harbor without dying.

**Comment by leatrix** [comment]
There is a guide [here](https://www.youtube.com/watch?v=6Oyrhkl75NI) but it requires some precision as well as a fair bit of running and swimming which adds onto the time.  Most people are just going to jump, die and release at Menethil especially given they are likely to be playing a low level character before they have unlocked the flight points.  So the tooltip is just to warn them that they should expect to die.

**Comment by economou** [comment]
Understandable; it turns out I just got extremely lucky on my first attempt.  I figured since I got it on the first try, it was easy.
