### ISSUE TITLE
Missing zone crossings, instance portals and some other things.

### ISSUE THREAD

**Issue by CaraleTheGnome** [leatrix/leatrix-maps-wrath#54]
Hi, I've spent some time going over the whole game map and I found some issues/ideas, hopefully some of it useful.

This is for TBC but most of these probably also apply to Classic and Wrath. Below I've mentioned every single one that I can think of, chances are that you've thought of a few of these but discarded them for being obvious or too cluttered but I figured I would mention them just in case.

**Missing/Incorrect Zone Crossings (as seen on each mentioned map):**
* (Missing) Hellfire Peninsula - The Dark Portal (The Stair of Destiny) to The Dark Portal in Blasted Lands.
* (Missing) Teldrassil - Crossing from Rut'Theran Village to Darnassus
* (Missing) Teldrassil - Crossing from Darnassus to Rut'Theran Village
* (Missing) Darnassus - Exit east to Teldrassil
* Darnassus - The zone crossing west just says "Teldrassil" but maybe it should also mention that it is the exit to Rut'Theran Village?
* (Missing) The Barrens - On the Orgrimmar map there is a zone crossing west to The Barrens, but I don't see any zone crossing from The Barrens to Orgrimmar on the map.
* Felwood - The north crossing into Timbermaw Hold should say "Moonglade, Winterspring" to be consistent with the zone crossing text on the Moonglade map.
* Winterspring - The west crossing into Timbermaw Hold should say "Felwood, Moonglade" to be consistent with the zone crossing text on the Moonglade map.
* The Exodar - Both of the zone crossings on this map first mention "Azuremyst Isle" and then either "The Vault of Lights" or "Seat of the Naaru" but I don't think it makes sense to keep the latter two texts since you are leaving these two places and going to Azuremyst Isle, not the other way around, at least on this map. It makes sense to keep those two texts on the Azuremyst Isle map though.

There are two additional missing zone crossings between the south of Darkshore and the north of Ashenvale, here are the coordinates and the names:
* Darkshore (Twilight Vale) at 37.2, 97.6 -> Ashenvale at 20.7, 15.9 - This is a road that you can see on the Ashenvale map.
* Darkshore (Twilight Shore) at 27.7, 93.1 -> Ashenvale (The Zoram Strand) at 9.9, 10.6 - You just walk along the wide beach here, no swimming required.

* (Missing) Zone crossing between Ghostlands at 76.0, 4.8 and Eversong Woods at 67.2, 87.4 - Wide piece of land that you just walk across.
* (Missing) Undercity - Through the sewers west into Tirisfal Glades.
* (Missing) Tirisfal Glades - Entrance to Undercity through the sewers side entrance.
* Eastern Plaguelands - While not a zone crossing per say it may be a good idea to add the tunnel entrance and exit through Terrorweb Tunnel from Thondroril River to Terrordale since it can be a big shortcut.
* Alterac Mountains - The north zone crossing should say Western PlagUelands. :)
* Alterac Mountains - If you follow the river east along the bank then you will enter Western Plaguelands, may be worth to add a zone crossing there as well. Alterac Mountains at 90.9, 47.1 and Western Plaguelands at 50.9, 95.7.
* Arathi Highlands - There is a secret path to Faldir's Cove not shown on the map, is it worth pointing it out or is that beyond the scope of the addon?
* (Missing) Blasted Lands - The Dark Portal to Hellfire Peninsula - The Dark Portal (The Stair of Destiny)
* (Missing) Silverpine Forest at 69.3, 53.5 - > Alterac Mountains (Dalaran) at 9.2, 71.9. A big wide path between the mountains.

**Instance Portals:**
* (Missing) Feralas - The side entrance portal to Dire Maul East is not shown. I'm aware that there are two portals to enter into east from inside Dire Maul but I mean the one way further east out in Feralas proper where a sad elf is.
* (Missing) Dun Morogh - There is a side entrance portal into Gnomeregan, maybe it is worth adding.
* (Missing) Badlands - There is a side entrance portal into Uldaman far away from the main entrance.

**Flight Master:**
* I don't see the Isle of Quel'Danas flight master marked on the map.

Gimme a poke should you want any more information about any of the stuff above. :)

**Comment by leatrix** [comment]
Many thanks for the effort you put into this.  Most of these have been added.
