### ISSUE TITLE
When map opacity is set to <100% and remove map border is disabled, the map shows a quest pane and list

### ISSUE THREAD

**Issue by acusano** [leatrix/leatrix-maps-wrath#55]
Using the latest version of the addon 3.0.00 in wratch classic prepatch. 

When "Set map opacity" is enabled and set to a value < 100% (either stationary or while moving) AND the "remove map border" option is disabled, it appears that a quest pane and list is overlayed onto of the map. You can faintly see in the screenshot below (I have set opacity to 50%) a pane to the right where I assume quests would be listed, and on the bottom left where the quest text and details would go.

I think this is a bug as before in BCC, only the full map would show in this type of view, and the corect behavior is displayed when "remove map border" is enabled.

![screenshot_1](https://user-images.githubusercontent.com/6808113/187707982-4371c533-963e-4812-a882-a568c1161480.png)

**Comment by leatrix** [comment]
Many thanks for the report and screenshot.  Should be fixed in 3.0.01.

**Comment by acusano** [comment]
Thanks @leatrix, can confirm working as expected in 3.0.04! Will close this issue.
