### ISSUE TITLE
Wrong icon and missing information for Dire Maul East side entrance.

### ISSUE THREAD

**Issue by CaraleTheGnome** [leatrix/leatrix-maps-wrath#58]
Heya, this doesn't look quite right:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/24671315/188334329-8a5b9ae1-00ce-4d40-b08c-422a79e2adab.png">

I think that is the wrong icon and it lacks information about instance levels and so on. Should also probably be called Dire Maul East (side entrance) to be consistent with the other side entrance portals, since it makes you enter DM East in a totally different place.
Not sure if it still requires the instance key to enter in Wrath or not, so may be worth mentioning if you can find that out.

**Comment by leatrix** [comment]
In 3.0.06.alpha.4, the side entrance icon is now a dungeon icon with the required information.
