### ISSUE TITLE
Reporting people in BG causes error, every time.

### ISSUE THREAD

**Issue by Nillx** [leatrix/leatrix-maps-wrath#62]
This have been an issue since classic release. Its impossible to right click report players from the map, im always getting this error. Had all my addons disabled (except Leatrix Plus and Bugsacks and Buggrabber). Getting the error even after reloading my UI, every time.

![image](https://user-images.githubusercontent.com/34476875/189397121-9b0b74c9-e597-4cbf-b14a-097e426b69d4.png)

```
2x [ADDON_ACTION_FORBIDDEN] AddOn 'Leatrix_Maps' tried to call the protected function 'ReportPlayerIsPVPAFK()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ReportPlayerIsPVPAFK'
[string "@Blizzard_SharedMapDataProviders\GroupMembersDataProvider.lua"]:201: in function `func'
[string "@FrameXML\UIDropDownMenu.lua"]:944: in function `UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
```

**Comment by Nillx** [comment]
Nvm i saw your reply from an earlier report, sucks that blizzard never fixed this.

**Comment by leatrix** [comment]
[Just linking this here for future reference.](https://github.com/leatrix/leatrix-maps-wrath/issues/56)

With few exceptions, Blizzard tend not to fix issues that only affect addons even if those addons are only affected because of bugs or coding issues in the game code.
