### ISSUE TITLE
Moving causes the map to flicker.

### ISSUE THREAD

**Issue by hvownij** [leatrix/leatrix-maps-wrath#63]
I want to use Leatrix maps with 100% visibility and not fadeout when im flying and mining.  However the slider to keep the visibility at 100% doesnt actually do what it is supposed to.  Moving around causes flickering and makes it annoying to use.

**Comment by leatrix** [comment]
You likely have another addon installed which is preventing LTM from setting the map opacity correctly.  Disable all other addons.  It should work fine.  Enable other addons gradually until you find the addon causing the problem.  You can then either disable that addon or tell me what it is and I can advise you further.

**Comment by Critzie** [comment]
I know its a closed issue but its 100% ElvUI [https://puu.sh/JmXNL/67a61fab91.png](url)
