### ISSUE TITLE
when u zoom in points of interest/markers go outside map window

### ISSUE THREAD

**Issue by manbats** [leatrix/leatrix-maps-wrath#64]
when you zoom in all the markers on the map spread across your screen. they go outside the map window.  so if you want to zoom in and have the ma p open you markers n points of interest all over the screen

**Comment by robmonte** [comment]
For what it's worth, I tried out another map addon called `ClassicWorldMapEnhanced` which has zooming as well, but that didn't have the same issue with the map icons. Not sure how that's handling them, but thought I'd mention it in case you would want to peek at its code.

**Comment by leatrix** [comment]
@robmonte When I tested it just now, Questie icons were shown outside of the map frame so it doesn't make any difference.

Steps to reproduce:

- Ensure only Enhanced WorldMap and Questie are loaded.
- Reload your UI.
- The moment your UI appears, press M to open the map (don't wait).
- Right-click to navigate to the continent map straight away (don't wait).
- Zoom in and drag the map.  Questie icons will be shown outside of the map frame.
- If you now wait for Questie to finish loading all of it's icons (takes a few seconds), then close and open the map, navigate back to the continent map and zoom and drag as before, the Questie icons will remain in the map frame.  This may be what you are referring to but this is identical to what happens with Leatrix Maps so I don't see any difference.

**Comment by manbats** [comment]
Dosnt matter hoe long inlet questie load the icons still go outside the map frame
  


@robmonte When I tested it just now, Questie icons were shown outside of the map frame so it doesn't make any difference.

Steps to reproduce:
   
   - Ensure only Enhanced WorldMap and Questie
   - Reload your UI.
   - The moment your UI appears, press M to open the map (don't wait).
   - Right-click to navigate to the continent map straight away (don't wait).
   - Zoom in and drag the map. Questie icons will be shown outside of the map frame.
   - If you now wait for Questie to finish loading all of it's icons (takes a few seconds), then close and open the map, navigate back to the continent map and zoom and drag as before, the Questie icons will remain in the map frame. This may be what you are referring to but this is identical to what happens with Leatrix Maps so I don't see any difference.

**Comment by leatrix** [comment]
There are several GitHub issues about this issue already.  It's nothing to do with LTM.
https://github.com/Questie/Questie/issues/4311
https://github.com/Questie/Questie/issues/3147
https://github.com/Questie/Questie/issues/1607

**Comment by manbats** [comment]
Ok....
  


There are several GitHub issues about this issue already. It's nothing to do with LTM.
Questie/Questie#4311
Questie/Questie#3147
Questie/Questie#1607
