### ISSUE TITLE
Can't close map with ESC key

### ISSUE THREAD

**Issue by Aurumai** [leatrix/leatrix-maps-wrath#65]
Not sure if this is a bug or just a lack of a feature, but I can't seem to adjust my muscle memory to press the map key again to close rather than just clearing my whole screen with ESC.  Would ***highly*** appreciate it if I could close the map with the ESC key, even if that wasn't enabled by default.

**Comment by leatrix** [comment]
In the configuration panel, ensure 'Sticky map frame' is disabled.  If it's already disabled, disable other addons and see if that helps.

**Comment by Aurumai** [comment]
Oh my god.  You're a legend and I'm an idiot.  Sorry, I *thought* I had browsed through all of the settings.  I guess I either missed it or just didn't understand the description and passed it over.  Thanks for clarifying.
