### ISSUE TITLE
Missing green arrow to Dalaran

### ISSUE THREAD

**Issue by Iowerth** [leatrix/leatrix-maps-wrath#70]
Hi. There is no green arrow to Dalaran.
Version 3.0.29.
![2022-10-22 18_33_17-World of Warcraft](https://user-images.githubusercontent.com/10152411/197347912-e5c11cd4-175e-44b7-aa74-c8f850bfd3e4.jpg)

**Comment by Iowerth** [comment]
Up.
It was the same issue year ago which was fixed very soon - https://github.com/leatrix/leatrix-maps-wrath/issues/51

**Comment by leatrix** [comment]
Thank you for your suggestion.

> 3.0.84 - 19th January 2023
> - For 'Show points of interest', clicking a travel icon or a portal icon will now show the destination map.  Clicking a dungeon or raid icon on a Northrend map will now show the dungeon map (as long as there is only one dungeon or raid assigned to the icon).  Added zeppelin and boat icons to the Borean Tundra and Howling Fjord maps.  **Added a Dalaran teleport crystal icon and a zone crossing icon to the Dalaran and Crystalsong Forest maps.**
>

**Comment by Iowerth** [comment]
Thank you very much!
