### ISSUE TITLE
Map covers some other addons' buttons that get added to the map

### ISSUE THREAD

**Issue by robmonte** [leatrix/leatrix-maps-wrath#73]
This isn't an issue with the addon, but more of a help request. My particular use case is the two addons "Enhanced Flight Map" and "RareScanner". They add buttons to the map to toggle visuals on/off. For some reason, these are drawing under the map instead of on top. I noticed the Hide Questie button is properly moving next to the map's X-button and am wondering why the other addons I mentioned (and presumably other addons that may exist) do not account for this.

My naive solution was to try setting those 2 addon buttons' frame strata higher but that didn't work. As I'm not very knowledgeable about addon development, I didn't know what else to consider.

**Comment by leatrix** [comment]
Please try 3.0.49.alpha.1 and let me know how you go on with it.  In CurseForge App, you can right-click LTM in your addon listing and change the release type to alpha.  You will then get the option to update to the latest alpha.  You can change it back to release anytime you like.

**Comment by robmonte** [comment]
It does work now (I noticed you already released it though). Thank you!
