### ISSUE TITLE
[Request] Better unexplored map area control

### ISSUE THREAD

**Issue by robmonte** [leatrix/leatrix-maps-wrath#74]
I think it would be handy to have a button on the the top of the map to quickly swap between showing unexplored areas of the map or not (Toggle to disable/enable this button?). Additionally, not requiring a UI reload for this would be ideal. I know some other map addons do not require this, so I wonder what they are doing differently to make that possible.

**Comment by leatrix** [comment]
A reveal toggle checkbox used to be in the addon but it was removed some time after reveal tinting was added (the ability to show unrevealed areas in a different color).  The UI reload is needed because the addon is modular - that is, code is not run at all for options that are not enabled.
