### ISSUE TITLE
Leatrix Maps stays in forefront when opening a new window

### ISSUE THREAD

**Issue by Charax30** [leatrix/leatrix-maps-wrath#76]
If I have Leatrix Maps open and then launch another window (e.g., "Character Info), the new window gets placed behind the Leatrix window (to make the new window covered by Leatrix Maps).

I have reverted back to the November 2 version where Leatrix Maps worked correctly.

Hope I explained that adequately. :)

**Comment by leatrix** [comment]
Please try the latest alpha release.

**Comment by leatrix** [comment]
In 3.0.64, the world map frame will behave as it did previously so it no longer stays on top.  For addons that use Krowi's World Map Buttons library, the buttons will no longer show on the map frame but Krowi should hopefully release an update that fixes that (he is aware of it).
