### ISSUE TITLE
Default map border is missing 

### ISSUE THREAD

**Issue by kbCodeman** [leatrix/leatrix-maps-wrath#77]
in 3.0.64 when using default map, the map border is missing

# 3.0.64
![3 0 64 ltm](https://user-images.githubusercontent.com/107101333/205685655-12d4c36f-f275-4e86-9884-1b83a84e99a6.png)

# 3.0.62
![3 0 62 ltm](https://user-images.githubusercontent.com/107101333/205685702-dd80e414-ef6f-468b-a58b-646c9924d1fb.png)

**Comment by leatrix** [comment]
Sorry about that and thanks for the bug report.  It's fixed in 3.0.65.
