### ISSUE TITLE
Krowi's World Map Buttons lib has updated

### ISSUE THREAD

**Issue by MyTechnoHunter** [leatrix/leatrix-maps-wrath#78]
as the title mentions Krowi updated his lib to account for strata changes in wraths recent update

it is now Krowi_WorldMapButtons-1.5

as such your locking out for that addon in the frameless map code can be updated..

```
		if LeaMapsLC["NoMapBorder"] == "On" then

			-- Reposition Krowi's World Map Buttons if installed
			if LibStub("Krowi_WorldMapButtons-1.4", true) then
				local lib = LibStub:GetLibrary("Krowi_WorldMapButtons-1.4")
				if lib and lib.SetOffsets then
					lib:SetOffsets(40, 0)
				end
			end
			if LibStub("Krowi_WorldMapButtons-1.5", true) then
				local lib = LibStub:GetLibrary("Krowi_WorldMapButtons-1.5")
				if lib and lib.SetOffsets then
					lib:SetOffsets(40, 0)
				end
			end
```

or perhaps something cleaner on your end? 
at any rate just reporting the update :) ty!

**Comment by leatrix** [comment]
Many thanks for reporting this.  Added to 3.0.106.

**Comment by leatrix** [comment]
Krowi has removed 1.5 and instead updated 1.4 to 1.4.4.  So the 1.5 code will be removed in the next LTM update as its no longer needed.
